version: '3'
services:
  web:
    image: clau/boss-compose:v2
    container_name: claus-container-compose
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - WATCHPACK_POLLING=true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]


# docker-compose up